--- #YAML:1.0
name:                Catalyst-View-CSS-Minifier-XS
version:             0.01
abstract:            Concenate and minify your CSS files.
license:             perl
author:              
    - Ivan Drinchev <drinchev@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Catalyst:                      5.64
    CSS::Minifier::XS:             0
    CSS::Squish:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
